# #####################################################################
# Automatically generated by qmake (2.01a) Do. Nov 5 21:42:26 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += helper.h \
    mainwindow.h \
    database.h \
    newbackupwizard.h
FORMS += mainwindow.ui
SOURCES += helper.cpp \
    main.cpp \
    mainwindow.cpp \
    database.cpp \
    newbackupwizard.cpp
