#############################################################################
# Makefile for building: datenfresserGui.app/Contents/MacOS/datenfresserGui
# Generated by qmake (2.01a) (Qt 4.5.3) on: Tue Feb 2 11:13:29 2010
# Project:  datenfresserGui.pro
# Template: app
# Command: /opt/local/bin/qmake-mac -macx -o Makefile datenfresserGui.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = /usr/bin/g++-4.2
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/opt/local/libexec/qt4-mac/mkspecs/macx-g++ -I. -I/opt/local/libexec/qt4-mac/lib/QtCore.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/include/QtCore -I/opt/local/libexec/qt4-mac/lib/QtGui.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/include/QtGui -I/opt/local/libexec/qt4-mac/lib/QtSql.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/include/QtSql -I/opt/local/libexec/qt4-mac/include -I. -I. -I. -F/opt/local/libexec/qt4-mac/lib
LINK          = /usr/bin/g++-4.2
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/opt/local/libexec/qt4-mac/lib -L/opt/local/libexec/qt4-mac/lib -framework QtSql -L/opt/local/lib -L/opt/local/libexec/qt4-mac/lib -F/opt/local/libexec/qt4-mac/lib -framework QtGui -framework Carbon -framework AppKit -lpng -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/bin/qmake-mac
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = helper.cpp \
		main.cpp \
		mainwindow.cpp \
		database.cpp \
		newbackupwizard.cpp moc_mainwindow.cpp \
		moc_newbackupwizard.cpp
OBJECTS       = helper.o \
		main.o \
		mainwindow.o \
		database.o \
		newbackupwizard.o \
		moc_mainwindow.o \
		moc_newbackupwizard.o
DIST          = /opt/local/libexec/qt4-mac/mkspecs/common/unix.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf \
		/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/dwarf2.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/debug.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86_64.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf \
		datenfresserGui.pro
QMAKE_TARGET  = datenfresserGui
DESTDIR       = 
TARGET        = datenfresserGui.app/Contents/MacOS/datenfresserGui

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile datenfresserGui.app/Contents/PkgInfo datenfresserGui.app/Contents/Resources/empty.lproj datenfresserGui.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) datenfresserGui.app/Contents/MacOS/ || $(MKDIR) datenfresserGui.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: datenfresserGui.pro  /opt/local/libexec/qt4-mac/mkspecs/macx-g++/qmake.conf /opt/local/libexec/qt4-mac/mkspecs/common/unix.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf \
		/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/dwarf2.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/debug.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86_64.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf \
		/opt/local/libexec/qt4-mac/lib/QtSql.framework/QtSql.prl \
		/opt/local/libexec/qt4-mac/lib/QtCore.framework/QtCore.prl \
		/opt/local/libexec/qt4-mac/lib/QtGui.framework/QtGui.prl
	$(QMAKE) -macx -o Makefile datenfresserGui.pro
/opt/local/libexec/qt4-mac/mkspecs/common/unix.conf:
/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf:
/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf:
/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri:
/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/dwarf2.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/debug.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86_64.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf:
/opt/local/libexec/qt4-mac/lib/QtSql.framework/QtSql.prl:
/opt/local/libexec/qt4-mac/lib/QtCore.framework/QtCore.prl:
/opt/local/libexec/qt4-mac/lib/QtGui.framework/QtGui.prl:
qmake:  FORCE
	@$(QMAKE) -macx -o Makefile datenfresserGui.pro

datenfresserGui.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) datenfresserGui.app/Contents || $(MKDIR) datenfresserGui.app/Contents 
	@$(DEL_FILE) datenfresserGui.app/Contents/PkgInfo
	@echo "APPL????" >datenfresserGui.app/Contents/PkgInfo
datenfresserGui.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) datenfresserGui.app/Contents/Resources || $(MKDIR) datenfresserGui.app/Contents/Resources 
	@touch datenfresserGui.app/Contents/Resources/empty.lproj
	
datenfresserGui.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) datenfresserGui.app/Contents || $(MKDIR) datenfresserGui.app/Contents 
	@$(DEL_FILE) datenfresserGui.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,datenfresserGui,g" -e "s,@TYPEINFO@,????,g" /opt/local/libexec/qt4-mac/mkspecs/macx-g++/Info.plist.app >datenfresserGui.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/datenfresserGui1.0.0 || $(MKDIR) .tmp/datenfresserGui1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/datenfresserGui1.0.0/ && $(COPY_FILE) --parents helper.h mainwindow.h database.h newbackupwizard.h .tmp/datenfresserGui1.0.0/ && $(COPY_FILE) --parents helper.cpp main.cpp mainwindow.cpp database.cpp newbackupwizard.cpp .tmp/datenfresserGui1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/datenfresserGui1.0.0/ && (cd `dirname .tmp/datenfresserGui1.0.0` && $(TAR) datenfresserGui1.0.0.tar datenfresserGui1.0.0 && $(COMPRESS) datenfresserGui1.0.0.tar) && $(MOVE) `dirname .tmp/datenfresserGui1.0.0`/datenfresserGui1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/datenfresserGui1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r datenfresserGui.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_newbackupwizard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_newbackupwizard.cpp
moc_mainwindow.cpp: database.h \
		helper.h \
		mainwindow.h
	/opt/local/libexec/qt4-mac/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_newbackupwizard.cpp: newbackupwizard.h
	/opt/local/libexec/qt4-mac/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ newbackupwizard.h -o moc_newbackupwizard.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/local/libexec/qt4-mac/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

helper.o: helper.cpp helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helper.o helper.cpp

main.o: main.cpp mainwindow.h \
		database.h \
		helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		database.h \
		helper.h \
		ui_mainwindow.h \
		newbackupwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

database.o: database.cpp database.h \
		helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

newbackupwizard.o: newbackupwizard.cpp newbackupwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newbackupwizard.o newbackupwizard.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_newbackupwizard.o: moc_newbackupwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newbackupwizard.o moc_newbackupwizard.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

